### ISSUE TITLE
[question / possible new feature] one player sleep

### ISSUE THREAD

**Issue by Gladuin** [Nuytemans-Dieter/BetterSleeping#104]
Hello,

I want to configure this plugin so that only one person needs to sleep, but I can only configure percentages. I would like a feature that would allow one single player to set the time to day.

Thanks in advance,
Gladuin

**Comment by Nuytemans-Dieter** [comment]
Hello Gladuin,

Thank you for your suggestion! A similar feature has been requested a few times before so I will plan this for the next complete rewrite of the plugin. It's possibly scheduled for this summer but I can't guarantee that yet.
In the meantime, you may want to set the percentage very low (0% for example) so that one player will be enough to skip the night.

Have a great day,
Dieter

**Comment by Gladuin** [comment]
Hey,

Thanks for responding, it's nice to know that this feature will be added in the rewrite. Setting the percentage to 0 works flawlessly on my small (15 players max, 2-3 players online most of the time) server for my friends by the way!

**Comment by Gladuin** [comment]
Whoops, accidentally closed it

**Comment by Nuytemans-Dieter** [comment]
> Thanks for responding, it's nice to know that this feature will be added in the rewrite.

No problem at all! Good to hear you're satisfied.

> Setting the percentage to 0 works flawlessly on my small (15 players max, 2-3 players online most of the time) server for my friends by the way!

No problem! Great to hear that this works for now. I hope you guys are having fun there!

> Whoops, accidentally closed it

Haha those buttons are really close to eachother, I've been there and done that.

**Comment by Nuytemans-Dieter** [comment]
This has been implemented in a beta build of v3.0.0
