### ISSUE TITLE
Sleeping during a storm

### ISSUE THREAD

**Issue by eodrambo** [Nuytemans-Dieter/BetterSleeping#177]
**Sleeping during a storm does nothing**

**To Reproduce**
1. /set weather thunder
2. sleep in a bed
3. nothing happens

**Expected behavior**
weather to clear

**Comment by Nuytemans-Dieter** [comment]
Hey! Thank you for letting me know this is an issue.
This is very likely the same cause as #169. But just to be sure, which mode are you using? Setter or smooth?

**Comment by eodrambo** [comment]
i tired in both, No dice. Prefer to use the smooth, its really nice

**Comment by Nuytemans-Dieter** [comment]
Thank you! I just realised my question was stupid. Sometimes there was an early return meant to reduce cpu usage.
That early return was removed in the fix for the mentioned issue (169). I'll close this for now as this should be fixed in 3.0.4 which is currently being tested by BetterSleeping's beta testers. Expect a release within 14 days :-)

**Comment by eodrambo** [comment]
Sounds good!
