### ISSUE TITLE
Ignoring sleep_delay

### ISSUE THREAD

**Issue by MCOnnell97** [Nuytemans-Dieter/BetterSleeping#49]
Hi, I have an issue where when the last person required to sleep enters their bed the server immediately jumps to day, ignoring the 'sleep_delay' in the config. I have set this to various numbers with no change. It's especially weird when there's only one person on the server (when I first tested the plugin) as you don't appear to even get in the bed.

 Hoping this is something you can fix. Thanks.

**Comment by Nuytemans-Dieter** [comment]
Thank you for contacting me!
It may not seem this way but it is an intended feature.
Spigot/Minecraft will set the time to day instantly on multiplayer servers when all players in a world are sleeping. Unfortunately this means that it would act quicker than my plugin, and when players get kicked out of bed because of the time set to day by default mechanics, they would receive messages that players left their bed and the night wouldn't be skipped. 

To counter this, I ignored sleep_delay **only** when all players in a world are sleeping. 
However, please let me know if this also happens when not all playes in a world are sleeping.
I'd be happy to take a look at your configuration.

**Comment by MCOnnell97** [comment]
Thanks for the quick response! That makes sense, I imagine it is just that. About to add it to our server so hopefully get some more testing done and will report back if there is anything. 

Thanks again.

**Comment by Nuytemans-Dieter** [comment]
No problem!
Great! I hope your players enjoy the plugin if you decide to add it.
I'll be here if there is anything!
